# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKE55TkHuHfkgLurwWC40qdKmDe3XUGe
"""

import os
import tensorflow as tf

model = tf.keras.applications.mobilenet_v2.MobileNetV2(
    input_shape=(224, 224, 3), weights='imagenet', classifier_activation='softmax'
)

from tensorflow.python.saved_model.save import save

save_dir = os.path.join('/tmp/', 'mobilenetv2/saved_model.h5')
model.save(save_dir)

!pip3 install tensorflowjs

!cd /tmp/mobilenetv2/
!tensorflowjs_converter --input_format=keras --output_format=tfjs_layers_model /tmp/mobilenetv2/saved_model.h5 /tmp/tfjs_mobilenetv2

!zip -r /tmp/tfjs_mobilenetv2.zip /tmp/tfjs_mobilenetv2

"""You can find the docs for the tfjs converter here: https://github.com/tensorflow/tfjs/tree/master/tfjs-converter

It is important to note, not all features that exist in other version of tf exist for tfjs.

If you happen to be running on a linux machine, you can use the tensorflow js converter wizard instead of needing to use the python converter.  You can find the docs on how to do that here: https:/codelabs.developers.google.com/codelabs/tensorflowjs-convert-python-savedmodel#0
"""